### ISSUE TITLE
hard-coded english lang string "Course"

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#106]
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/classes/forms/filter_report_form.php#L54

**Comment by danmarsden** [comment]
another hard-coded string here:
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/templates/user_table.mustache#L86

**Comment by nawazsharif** [comment]
This issue has been solved
