### ISSUE TITLE
should the fullname() api be used instead of using the manual firstname . lastname display?

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#107]
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/classes/forms/user_report_form.php#L149

usually when displaying a users name we use the fullname() api to ensure it displays the detail in teh right order (and using the right fields, because some sites may configure different name fields.

**Comment by danmarsden** [comment]
another one here that might need to be changed: 
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/renderer.php#L81

**Comment by nawazsharif** [comment]
this issue has been solved
