### ISSUE TITLE
Plugin cannot be properly installed in Moodle 4.0

### ISSUE THREAD

**Issue by sumaiyamannan** [cursiveinc/moodle-tinymce_cursive#61]
Hi,
The plugin fail to install on Moodle 4.0
I have tested with: 

- Plugin branch: main
- PHP 7.4
- Postgres 12

The plugin is to be installed in   lib/editor/tiny/plugins/cursive folder but 4.0 only has tinymce folder. And when it is installed in 'tiny' folder the installation is ignored. If additional steps are needed for installation, can they be mentioned in the README file?

Regards,
Sumaiya

**Comment by nawazsharif** [comment]
We will work on this version later
