### ISSUE TITLE
does this support postgres?

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#83]
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/csvexport.php#L102

this looks like it's missing a bunch of group by fields that I would expect to fail on a postgres install - have you checked to see if the export works in postgres?

**Comment by nawazsharif** [comment]
@danmarsden issue has been resolved 
You could check now 
https://github.com/cursiveinc/moodle-tinymce_cursive/tree/MOODLE_404_STABLE
