### ISSUE TITLE
security checks should occur before the file is generated

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#84]
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/download_json.php#L36

it looks like the file is generated and then it checks "can the user access it" - it would be better to move that around so that it only generates a file if the user is actually allowed to download it.

Ideally I'd like to see a require_capability() call in there rather than the has_capability checks.

also - it's prefeerable not to put inline php code and functions in the same file. the "filestream" function also violates the frankenstyle naming rules.

**Comment by nawazsharif** [comment]
@danmarsden 
this issue has been solved
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/download_json.php#L37
