### ISSUE TITLE
frankenstyle naming violations

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#91]
the functions in your locallib.php do not follow the frankenstyle naming rules:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

function names like "get_user_attempts_data" and "create_token_for_user" are incorrect.

this is typically a blocker for plugins db approval

**Comment by danmarsden** [comment]
also the classes "filterreportform", "settimerform", "userreportform", "wrreportform" are not namespaced so break the frankenstyle naming rules and will need to be fixed.

they are already in your classes/forms folder so if you put:
namespace editor_tiny\cursive\forms;

at the top of those files (like your fileupload class) - it will allow class autoloading to work so you won't need to use the require_once() calls to include them where you need them too.

**Comment by mudrd8mz** [comment]
+1 to get these fixed before the approval. Thanks Dan!

**Comment by nawazsharif** [comment]
@mudrd8mz @danmarsden 
this issue has been solved 
you could check now 
https://github.com/cursiveinc/moodle-tinymce_cursive/commit/07133a4eb5d8b0db72b940abd137aa5e22c54021
Thank you
