### ISSUE TITLE
please don't call curl_init directly

### ISSUE THREAD

**Issue by danmarsden** [cursiveinc/moodle-tinymce_cursive#93]
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/lib.php#L197

Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

This isn't documented all that well, but do a search on moodle core for "curl" and you should see examples.

This wrapper class takes care of various security and proxy controls.

**Comment by nawazsharif** [comment]
This issue has been resolved
https://github.com/cursiveinc/moodle-tinymce_cursive/blob/main/lib.php#L197
